name          'garethr-garethr'
version       '0.0.1'
author        'garethr'
license       'Apache License, Version 2.0'
summary       'Module to allow installation of packages from packages.garethrushgrove.com'
project_page  'https://github.com/garethr/garethr-garethr'
dependency    'puppetlabs/apt'
